import { Subject } from './types';

export const agenticAISubject: Subject = {
  id: 'agentic-ai',
  name: 'Agentic AI',
  description: 'AI systems that can autonomously take actions, make decisions, and complete tasks with minimal human intervention',
  keywords: [
    'agentic ai',
    'ai agents',
    'autonomous ai',
    'ai autonomy',
    'agent-based ai',
    'ai agent',
    'autonomous agents',
    'agentic systems',
    'agentic',
  ],
  relatedTerms: [
    'llm agents',
    'large language model agents',
    'autonomous systems',
    'ai automation',
    'intelligent agents',
    'multi-agent',
    'agent framework',
    'langchain',
    'autogpt',
    'auto-gpt',
    'babyagi',
    'crewai',
    'autogen',
    'agent orchestration',
    'tool use',
    'function calling',
    'reasoning agents',
    'planning agents',
    'task automation',
    'ai assistants',
    'copilot',
    'devin',
    'cognition ai',
    'openai agents',
    'anthropic claude',
    'gemini agents',
  ],
};
